[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "random_choice"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = []
[tool.setuptools.package-data]
"random_choice" = ["py.typed"]
[tool.setuptools.packages.find]
where = ["src"]
